name: leadbook_online
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  getwidget: ^3.0.1
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.10.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - .env
    - assets/
  uses-material-design: true

